version: '3.8'

# Services
services:

  # Spark Master
  spark-master:
    container_name: spark-master
    image: owshq-spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "8080:8080"  # Spark Master Web UI
    volumes:
      - ${APP_SRC_PATH}:/opt/bitnami/spark/jobs
      - ${APP_STORAGE_PATH}:/opt/bitnami/spark/storage
      - ${APP_LOG_PATH}:/opt/bitnami/spark/logs/events

  # Spark Workers
  spark-worker-1:
    container_name: spark-worker-1
    image: owshq-spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ${APP_SRC_PATH}:/opt/bitnami/spark/jobs
      - ${APP_STORAGE_PATH}:/opt/bitnami/spark/storage
      - ${APP_LOG_PATH}:/opt/bitnami/spark/logs/events
    depends_on:
      - spark-master

  spark-worker-2:
    container_name: spark-worker-2
    image: owshq-spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ${APP_SRC_PATH}:/opt/bitnami/spark/jobs
      - ${APP_STORAGE_PATH}:/opt/bitnami/spark/storage
      - ${APP_LOG_PATH}:/opt/bitnami/spark/logs/events
    depends_on:
      - spark-master

  spark-worker-3:
    container_name: spark-worker-3
    image: owshq-spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ${APP_SRC_PATH}:/opt/bitnami/spark/jobs
      - ${APP_STORAGE_PATH}:/opt/bitnami/spark/storage
      - ${APP_LOG_PATH}:/opt/bitnami/spark/logs/events
    depends_on:
      - spark-master

 # Spark History Server
  spark-history-server:
    container_name: spark-history-server
    image: owshq-spark-history-server:3.5
    environment:
      - SPARK_HISTORY_UI_PORT=18080
      - SPARK_DAEMON_MEMORY=5g
      - SPARK_HISTORY_RETAINEDAPPLICATIONS=100
      - SPARK_HISTORY_UI_MAXAPPLICATIONS=50
      - SPARK_HISTORY_STORE_MAXDISKUSAGE=20g
      - SPARK_HISTORY_FS_LOG_DIRECTORY=/opt/bitnami/spark/logs/events
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/bitnami/spark/logs/events
    ports:
      - 18080:18080
      - 4040:4040
    volumes:
      - ${APP_LOG_PATH}:/opt/bitnami/spark/logs/events
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
